// City list for the location autocomplete. Each entry has a state/province
// abbreviation and an ISO2 country code, shown as "City, ST, CC".
export type CityLocation = { city: string; state: string; country: string };

export const CITY_LOCATIONS: CityLocation[] = [
  // Pakistan — Punjab (PB)
  { city: "Lahore", state: "PB", country: "PK" },
  { city: "Faisalabad", state: "PB", country: "PK" },
  { city: "Rawalpindi", state: "PB", country: "PK" },
  { city: "Multan", state: "PB", country: "PK" },
  { city: "Gujranwala", state: "PB", country: "PK" },
  { city: "Sialkot", state: "PB", country: "PK" },
  { city: "Bahawalpur", state: "PB", country: "PK" },
  { city: "Sargodha", state: "PB", country: "PK" },
  { city: "Sahiwal", state: "PB", country: "PK" },
  { city: "Rahim Yar Khan", state: "PB", country: "PK" },
  { city: "Gujrat", state: "PB", country: "PK" },
  { city: "Sheikhupura", state: "PB", country: "PK" },
  { city: "Jhang", state: "PB", country: "PK" },
  { city: "Kasur", state: "PB", country: "PK" },
  { city: "Okara", state: "PB", country: "PK" },
  { city: "Dera Ghazi Khan", state: "PB", country: "PK" },
  { city: "Bahawalnagar", state: "PB", country: "PK" },
  { city: "Muzaffargarh", state: "PB", country: "PK" },
  // Pakistan — Sindh (SD)
  { city: "Karachi", state: "SD", country: "PK" },
  { city: "Hyderabad", state: "SD", country: "PK" },
  { city: "Sukkur", state: "SD", country: "PK" },
  { city: "Larkana", state: "SD", country: "PK" },
  { city: "Nawabshah", state: "SD", country: "PK" },
  { city: "Mirpur Khas", state: "SD", country: "PK" },
  // Pakistan — Khyber Pakhtunkhwa (KP)
  { city: "Peshawar", state: "KP", country: "PK" },
  { city: "Mardan", state: "KP", country: "PK" },
  { city: "Abbottabad", state: "KP", country: "PK" },
  { city: "Swat", state: "KP", country: "PK" },
  { city: "Kohat", state: "KP", country: "PK" },
  // Pakistan — Balochistan (BA), Islamabad (IS), AJK, GB
  { city: "Quetta", state: "BA", country: "PK" },
  { city: "Gwadar", state: "BA", country: "PK" },
  { city: "Islamabad", state: "IS", country: "PK" },
  { city: "Muzaffarabad", state: "AJK", country: "PK" },
  { city: "Mirpur", state: "AJK", country: "PK" },
  { city: "Gilgit", state: "GB", country: "PK" },
  // India
  { city: "Mumbai", state: "MH", country: "IN" },
  { city: "Delhi", state: "DL", country: "IN" },
  { city: "Bangalore", state: "KA", country: "IN" },
  { city: "Hyderabad", state: "TG", country: "IN" },
  { city: "Chennai", state: "TN", country: "IN" },
  { city: "Kolkata", state: "WB", country: "IN" },
  { city: "Pune", state: "MH", country: "IN" },
  { city: "Lahore", state: "PB", country: "IN" },
  // Bangladesh
  { city: "Dhaka", state: "DH", country: "BD" },
  { city: "Chittagong", state: "CT", country: "BD" },
  // United States
  { city: "New York", state: "NY", country: "US" },
  { city: "Los Angeles", state: "CA", country: "US" },
  { city: "San Francisco", state: "CA", country: "US" },
  { city: "Chicago", state: "IL", country: "US" },
  { city: "Houston", state: "TX", country: "US" },
  { city: "Austin", state: "TX", country: "US" },
  { city: "Seattle", state: "WA", country: "US" },
  { city: "Boston", state: "MA", country: "US" },
  { city: "Miami", state: "FL", country: "US" },
  { city: "Atlanta", state: "GA", country: "US" },
  // United Kingdom
  { city: "London", state: "ENG", country: "GB" },
  { city: "Manchester", state: "ENG", country: "GB" },
  { city: "Birmingham", state: "ENG", country: "GB" },
  { city: "Edinburgh", state: "SCT", country: "GB" },
  // Canada
  { city: "Toronto", state: "ON", country: "CA" },
  { city: "Vancouver", state: "BC", country: "CA" },
  { city: "Montreal", state: "QC", country: "CA" },
  // UAE & Middle East
  { city: "Dubai", state: "DU", country: "AE" },
  { city: "Abu Dhabi", state: "AZ", country: "AE" },
  { city: "Riyadh", state: "RD", country: "SA" },
  { city: "Doha", state: "DA", country: "QA" },
  // Australia
  { city: "Sydney", state: "NSW", country: "AU" },
  { city: "Melbourne", state: "VIC", country: "AU" },
  // Europe
  { city: "Berlin", state: "BE", country: "DE" },
  { city: "Munich", state: "BY", country: "DE" },
  { city: "Paris", state: "IDF", country: "FR" },
  { city: "Madrid", state: "MD", country: "ES" },
  { city: "Amsterdam", state: "NH", country: "NL" },
  // Asia
  { city: "Singapore", state: "SG", country: "SG" },
  { city: "Kuala Lumpur", state: "KL", country: "MY" },
  { city: "Tokyo", state: "TK", country: "JP" },

  // ---- expanded set ----
  // Pakistan (more)
  { city: "Wah Cantonment", state: "PB", country: "PK" },
  { city: "Chiniot", state: "PB", country: "PK" },
  { city: "Kamoke", state: "PB", country: "PK" },
  { city: "Hafizabad", state: "PB", country: "PK" },
  { city: "Mandi Bahauddin", state: "PB", country: "PK" },
  { city: "Jhelum", state: "PB", country: "PK" },
  { city: "Khanewal", state: "PB", country: "PK" },
  { city: "Vehari", state: "PB", country: "PK" },
  { city: "Burewala", state: "PB", country: "PK" },
  { city: "Kohat", state: "KP", country: "PK" },
  { city: "Dera Ismail Khan", state: "KP", country: "PK" },
  { city: "Mingora", state: "KP", country: "PK" },
  { city: "Nowshera", state: "KP", country: "PK" },
  { city: "Sahiwal", state: "PB", country: "PK" },
  { city: "Turbat", state: "BA", country: "PK" },
  { city: "Khuzdar", state: "BA", country: "PK" },
  { city: "Sukkur", state: "SD", country: "PK" },
  { city: "Jacobabad", state: "SD", country: "PK" },
  { city: "Shikarpur", state: "SD", country: "PK" },
  { city: "Tando Adam", state: "SD", country: "PK" },
  // India (more)
  { city: "Ahmedabad", state: "GJ", country: "IN" },
  { city: "Surat", state: "GJ", country: "IN" },
  { city: "Jaipur", state: "RJ", country: "IN" },
  { city: "Lucknow", state: "UP", country: "IN" },
  { city: "Kanpur", state: "UP", country: "IN" },
  { city: "Nagpur", state: "MH", country: "IN" },
  { city: "Indore", state: "MP", country: "IN" },
  { city: "Bhopal", state: "MP", country: "IN" },
  { city: "Chandigarh", state: "CH", country: "IN" },
  { city: "Kochi", state: "KL", country: "IN" },
  // United States (more)
  { city: "San Diego", state: "CA", country: "US" },
  { city: "San Jose", state: "CA", country: "US" },
  { city: "Dallas", state: "TX", country: "US" },
  { city: "Phoenix", state: "AZ", country: "US" },
  { city: "Philadelphia", state: "PA", country: "US" },
  { city: "Denver", state: "CO", country: "US" },
  { city: "Portland", state: "OR", country: "US" },
  { city: "Las Vegas", state: "NV", country: "US" },
  { city: "Washington", state: "DC", country: "US" },
  { city: "Nashville", state: "TN", country: "US" },
  { city: "Charlotte", state: "NC", country: "US" },
  { city: "Detroit", state: "MI", country: "US" },
  { city: "Minneapolis", state: "MN", country: "US" },
  { city: "Orlando", state: "FL", country: "US" },
  // UK & Ireland (more)
  { city: "Leeds", state: "ENG", country: "GB" },
  { city: "Glasgow", state: "SCT", country: "GB" },
  { city: "Liverpool", state: "ENG", country: "GB" },
  { city: "Bristol", state: "ENG", country: "GB" },
  { city: "Cardiff", state: "WLS", country: "GB" },
  { city: "Belfast", state: "NIR", country: "GB" },
  { city: "Dublin", state: "L", country: "IE" },
  { city: "Cork", state: "M", country: "IE" },
  // Canada (more)
  { city: "Calgary", state: "AB", country: "CA" },
  { city: "Edmonton", state: "AB", country: "CA" },
  { city: "Ottawa", state: "ON", country: "CA" },
  { city: "Mississauga", state: "ON", country: "CA" },
  { city: "Winnipeg", state: "MB", country: "CA" },
  // Australia & NZ (more)
  { city: "Brisbane", state: "QLD", country: "AU" },
  { city: "Perth", state: "WA", country: "AU" },
  { city: "Adelaide", state: "SA", country: "AU" },
  { city: "Auckland", state: "AUK", country: "NZ" },
  { city: "Wellington", state: "WGN", country: "NZ" },
  // Middle East (more)
  { city: "Sharjah", state: "SH", country: "AE" },
  { city: "Jeddah", state: "MK", country: "SA" },
  { city: "Dammam", state: "EP", country: "SA" },
  { city: "Kuwait City", state: "KU", country: "KW" },
  { city: "Manama", state: "MN", country: "BH" },
  { city: "Muscat", state: "MA", country: "OM" },
  { city: "Amman", state: "AM", country: "JO" },
  { city: "Istanbul", state: "34", country: "TR" },
  { city: "Ankara", state: "06", country: "TR" },
  // Europe (more)
  { city: "Hamburg", state: "HH", country: "DE" },
  { city: "Frankfurt", state: "HE", country: "DE" },
  { city: "Barcelona", state: "CT", country: "ES" },
  { city: "Lyon", state: "ARA", country: "FR" },
  { city: "Milan", state: "LOM", country: "IT" },
  { city: "Rome", state: "LAZ", country: "IT" },
  { city: "Rotterdam", state: "ZH", country: "NL" },
  { city: "Lisbon", state: "LI", country: "PT" },
  { city: "Warsaw", state: "MZ", country: "PL" },
  { city: "Stockholm", state: "AB", country: "SE" },
  { city: "Zurich", state: "ZH", country: "CH" },
  { city: "Vienna", state: "W", country: "AT" },
  // Asia (more)
  { city: "Bangkok", state: "BK", country: "TH" },
  { city: "Jakarta", state: "JK", country: "ID" },
  { city: "Manila", state: "MM", country: "PH" },
  { city: "Cebu City", state: "CB", country: "PH" },
  { city: "Ho Chi Minh City", state: "SG", country: "VN" },
  { city: "Hanoi", state: "HN", country: "VN" },
  { city: "Hong Kong", state: "HK", country: "HK" },
  { city: "Shanghai", state: "SH", country: "CN" },
  { city: "Beijing", state: "BJ", country: "CN" },
  { city: "Shenzhen", state: "GD", country: "CN" },
  { city: "Seoul", state: "SE", country: "KR" },
  { city: "Osaka", state: "OS", country: "JP" },
  { city: "Colombo", state: "WP", country: "LK" },
  { city: "Kathmandu", state: "BA", country: "NP" },
  // Africa
  { city: "Cairo", state: "C", country: "EG" },
  { city: "Lagos", state: "LA", country: "NG" },
  { city: "Abuja", state: "FC", country: "NG" },
  { city: "Nairobi", state: "NB", country: "KE" },
  { city: "Johannesburg", state: "GP", country: "ZA" },
  { city: "Cape Town", state: "WC", country: "ZA" },
  { city: "Casablanca", state: "CA", country: "MA" },
  { city: "Accra", state: "AA", country: "GH" },
  // South America
  { city: "Sao Paulo", state: "SP", country: "BR" },
  { city: "Rio de Janeiro", state: "RJ", country: "BR" },
  { city: "Buenos Aires", state: "BA", country: "AR" },
  { city: "Bogota", state: "DC", country: "CO" },
  { city: "Lima", state: "LIM", country: "PE" },
  { city: "Santiago", state: "RM", country: "CL" },
  { city: "Mexico City", state: "CMX", country: "MX" },

  // ---- global expansion (major + secondary cities worldwide) ----
  // Pakistan (district-level, more)
  { city: "Sadiqabad", state: "PB", country: "PK" },
  { city: "Khanpur", state: "PB", country: "PK" },
  { city: "Lodhran", state: "PB", country: "PK" },
  { city: "Pakpattan", state: "PB", country: "PK" },
  { city: "Toba Tek Singh", state: "PB", country: "PK" },
  { city: "Mianwali", state: "PB", country: "PK" },
  { city: "Bhakkar", state: "PB", country: "PK" },
  { city: "Layyah", state: "PB", country: "PK" },
  { city: "Rajanpur", state: "PB", country: "PK" },
  { city: "Attock", state: "PB", country: "PK" },
  { city: "Chakwal", state: "PB", country: "PK" },
  { city: "Narowal", state: "PB", country: "PK" },
  { city: "Khairpur", state: "SD", country: "PK" },
  { city: "Dadu", state: "SD", country: "PK" },
  { city: "Thatta", state: "SD", country: "PK" },
  { city: "Badin", state: "SD", country: "PK" },
  { city: "Bannu", state: "KP", country: "PK" },
  { city: "Mansehra", state: "KP", country: "PK" },
  { city: "Charsadda", state: "KP", country: "PK" },
  { city: "Sibi", state: "BA", country: "PK" },
  { city: "Chaman", state: "BA", country: "PK" },
  { city: "Skardu", state: "GB", country: "PK" },
  // India (more states)
  { city: "Patna", state: "BR", country: "IN" },
  { city: "Bhubaneswar", state: "OD", country: "IN" },
  { city: "Guwahati", state: "AS", country: "IN" },
  { city: "Visakhapatnam", state: "AP", country: "IN" },
  { city: "Coimbatore", state: "TN", country: "IN" },
  { city: "Vadodara", state: "GJ", country: "IN" },
  { city: "Ludhiana", state: "PB", country: "IN" },
  { city: "Agra", state: "UP", country: "IN" },
  { city: "Nashik", state: "MH", country: "IN" },
  { city: "Thiruvananthapuram", state: "KL", country: "IN" },
  // United States (more)
  { city: "Sacramento", state: "CA", country: "US" },
  { city: "San Antonio", state: "TX", country: "US" },
  { city: "Columbus", state: "OH", country: "US" },
  { city: "Indianapolis", state: "IN", country: "US" },
  { city: "Pittsburgh", state: "PA", country: "US" },
  { city: "Salt Lake City", state: "UT", country: "US" },
  { city: "Kansas City", state: "MO", country: "US" },
  { city: "Raleigh", state: "NC", country: "US" },
  { city: "Tampa", state: "FL", country: "US" },
  { city: "St. Louis", state: "MO", country: "US" },
  // Canada / UK / Europe (more)
  { city: "Quebec City", state: "QC", country: "CA" },
  { city: "Hamilton", state: "ON", country: "CA" },
  { city: "Halifax", state: "NS", country: "CA" },
  { city: "Sheffield", state: "ENG", country: "GB" },
  { city: "Newcastle", state: "ENG", country: "GB" },
  { city: "Nottingham", state: "ENG", country: "GB" },
  { city: "Cologne", state: "NW", country: "DE" },
  { city: "Stuttgart", state: "BW", country: "DE" },
  { city: "Marseille", state: "PAC", country: "FR" },
  { city: "Valencia", state: "VC", country: "ES" },
  { city: "Seville", state: "AN", country: "ES" },
  { city: "Naples", state: "CAM", country: "IT" },
  { city: "Turin", state: "PIE", country: "IT" },
  { city: "Munich", state: "BY", country: "DE" },
  { city: "Porto", state: "PO", country: "PT" },
  { city: "Krakow", state: "MA", country: "PL" },
  { city: "Gothenburg", state: "O", country: "SE" },
  { city: "Geneva", state: "GE", country: "CH" },
  { city: "Brussels", state: "BU", country: "BE" },
  { city: "Antwerp", state: "VAN", country: "BE" },
  { city: "Copenhagen", state: "84", country: "DK" },
  { city: "Oslo", state: "03", country: "NO" },
  { city: "Helsinki", state: "18", country: "FI" },
  { city: "Athens", state: "I", country: "GR" },
  { city: "Bucharest", state: "B", country: "RO" },
  { city: "Budapest", state: "BU", country: "HU" },
  { city: "Prague", state: "PR", country: "CZ" },
  { city: "Kyiv", state: "30", country: "UA" },
  { city: "Moscow", state: "MOW", country: "RU" },
  { city: "Saint Petersburg", state: "SPE", country: "RU" },
  // Asia (more)
  { city: "Chiang Mai", state: "CM", country: "TH" },
  { city: "Surabaya", state: "JI", country: "ID" },
  { city: "Bandung", state: "JB", country: "ID" },
  { city: "Davao City", state: "DC", country: "PH" },
  { city: "Da Nang", state: "DN", country: "VN" },
  { city: "Guangzhou", state: "GD", country: "CN" },
  { city: "Chengdu", state: "SC", country: "CN" },
  { city: "Busan", state: "BU", country: "KR" },
  { city: "Yokohama", state: "KN", country: "JP" },
  { city: "Nagoya", state: "AI", country: "JP" },
  { city: "Taipei", state: "TPE", country: "TW" },
  { city: "Kaohsiung", state: "KHH", country: "TW" },
  { city: "Almaty", state: "ALA", country: "KZ" },
  { city: "Tashkent", state: "TK", country: "UZ" },
  { city: "Baku", state: "BA", country: "AZ" },
  { city: "Tehran", state: "07", country: "IR" },
  { city: "Baghdad", state: "BG", country: "IQ" },
  { city: "Beirut", state: "BA", country: "LB" },
  { city: "Damascus", state: "DI", country: "SY" },
  // Africa (more)
  { city: "Alexandria", state: "ALX", country: "EG" },
  { city: "Kano", state: "KN", country: "NG" },
  { city: "Port Harcourt", state: "RI", country: "NG" },
  { city: "Mombasa", state: "MB", country: "KE" },
  { city: "Dar es Salaam", state: "DS", country: "TZ" },
  { city: "Addis Ababa", state: "AA", country: "ET" },
  { city: "Kampala", state: "KLA", country: "UG" },
  { city: "Durban", state: "KZN", country: "ZA" },
  { city: "Pretoria", state: "GP", country: "ZA" },
  { city: "Rabat", state: "RA", country: "MA" },
  { city: "Marrakesh", state: "MR", country: "MA" },
  { city: "Tunis", state: "TU", country: "TN" },
  { city: "Algiers", state: "AL", country: "DZ" },
  { city: "Dakar", state: "DK", country: "SN" },
  { city: "Kumasi", state: "AH", country: "GH" },
  // Americas (more)
  { city: "Brasilia", state: "DF", country: "BR" },
  { city: "Belo Horizonte", state: "MG", country: "BR" },
  { city: "Curitiba", state: "PR", country: "BR" },
  { city: "Guadalajara", state: "JA", country: "MX" },
  { city: "Monterrey", state: "NL", country: "MX" },
  { city: "Medellin", state: "ANT", country: "CO" },
  { city: "Quito", state: "P", country: "EC" },
  { city: "Caracas", state: "DC", country: "VE" },
  { city: "Montevideo", state: "MO", country: "UY" },
  { city: "La Paz", state: "L", country: "BO" },
  { city: "Panama City", state: "8", country: "PA" },
  { city: "San Jose", state: "SJ", country: "CR" },
];

export function cityLabel(c: CityLocation) {
  return `${c.city}, ${c.state}, ${c.country}`;
}
