// Common degrees for the Degree autocomplete. Users can also type any degree
// not in the list (the field accepts free text).
export const DEGREES: string[] = [
  "High School Diploma",
  "Associate Degree",
  "Diploma",
  "Certificate",
  "Bachelors",
  "Bachelor of Science (BSc)",
  "Bachelor of Arts (BA)",
  "Bachelor of Engineering (BE)",
  "Bachelor of Technology (BTech)",
  "Bachelor of Computer Science (BCS)",
  "Bachelor of Business Administration (BBA)",
  "Bachelor of Commerce (BCom)",
  "Bachelor of Fine Arts (BFA)",
  "Bachelor of Laws (LLB)",
  "Bachelor of Medicine (MBBS)",
  "Masters",
  "Master of Science (MSc)",
  "Master of Arts (MA)",
  "Master of Business Administration (MBA)",
  "Master of Information Technology (MIT)",
  "Master of Computer Science (MCS)",
  "Master of Engineering (ME)",
  "Master of Technology (MTech)",
  "Master of Commerce (MCom)",
  "Master of Fine Arts (MFA)",
  "Master of Laws (LLM)",
  "Master of Public Administration (MPA)",
  "Master of Public Health (MPH)",
  "Doctor of Philosophy (PhD)",
  "Doctor of Medicine (MD)",
  "Doctor of Education (EdD)",
  "Postgraduate Diploma",
  "Vocational Training",
];
