// Canonical world time-zone list for every picker in Xwork (contact info,
// company contacts, etc.). Each entry pairs the human label shown in the
// dropdown with an IANA zone id stored in the database — keeping the friendly
// "UTC±hh:mm City" wording while still letting <LocalTime> compute an accurate
// live clock (toLocaleTimeString needs an IANA id, not an offset string).
export type TimezoneOption = { value: string; label: string };

export const TIMEZONES: TimezoneOption[] = [
  { value: "Pacific/Midway", label: "UTC-11:00 Midway Island, Samoa" },
  { value: "Pacific/Honolulu", label: "UTC-10:00 Hawaii" },
  { value: "America/Anchorage", label: "UTC-08:00 Alaska" },
  { value: "America/Tijuana", label: "UTC-07:00 Pacific Time (US & Canada); Tijuana" },
  { value: "America/Phoenix", label: "UTC-07:00 Arizona" },
  { value: "America/Los_Angeles", label: "UTC-07:00 Pacific Time (US & Canada); Los Angeles" },
  { value: "America/Managua", label: "UTC-06:00 Nicaragua" },
  { value: "America/Regina", label: "UTC-06:00 Saskatchewan" },
  { value: "America/Denver", label: "UTC-06:00 Mountain Time (US & Canada)" },
  { value: "America/Mexico_City", label: "UTC-06:00 Mexico City, Tegucigalpa" },
  { value: "America/Bogota", label: "UTC-05:00 Bogota, Lima" },
  { value: "America/Chicago", label: "UTC-05:00 Central Time (US & Canada)" },
  { value: "America/Indiana/Knox", label: "UTC-05:00 Eastern Time - Indiana - Starke County" },
  { value: "America/New_York", label: "UTC-04:00 Eastern Time (US & Canada)" },
  { value: "America/Indiana/Indianapolis", label: "UTC-04:00 Eastern Time - Indiana - most locations" },
  { value: "America/Caracas", label: "UTC-04:00 Caracas" },
  { value: "America/La_Paz", label: "UTC-04:00 La Paz" },
  { value: "America/Sao_Paulo", label: "UTC-03:00 S & SE Brazil (GO, DF, MG, ES, RJ, SP, PR, SC, RS)" },
  { value: "America/Halifax", label: "UTC-03:00 Atlantic Time (Canada)" },
  { value: "America/Fortaleza", label: "UTC-03:00 NE Brazil (MA, PI, CE, RN, PB)" },
  { value: "America/Recife", label: "UTC-03:00 Pernambuco" },
  { value: "America/Argentina/Buenos_Aires", label: "UTC-03:00 E Argentina (BA, DF, SC, TF)" },
  { value: "America/St_Johns", label: "UTC-02:30 Newfoundland" },
  { value: "America/Noronha", label: "UTC-02:00 Mid-Atlantic" },
  { value: "Atlantic/Azores", label: "UTC Azores, Cape Verde Island" },
  { value: "UTC", label: "UTC (Coordinated Universal Time)" },
  { value: "Europe/Lisbon", label: "UTC+01:00 Lisbon" },
  { value: "Europe/London", label: "UTC+01:00 (Coordinated Universal Time) Dublin, Edinburgh, London" },
  { value: "Africa/Casablanca", label: "UTC+01:00 (no DST) Tangiers, Casablanca" },
  { value: "Africa/Algiers", label: "UTC+01:00 Algeria" },
  { value: "Europe/Berlin", label: "UTC+02:00 Berlin, Stockholm, Rome, Bern, Brussels" },
  { value: "Africa/Johannesburg", label: "UTC+02:00 Harare, Pretoria" },
  { value: "Europe/Paris", label: "UTC+02:00 Paris, Madrid" },
  { value: "Europe/Warsaw", label: "UTC+02:00 Prague, Warsaw" },
  { value: "Africa/Cairo", label: "UTC+03:00 Cairo" },
  { value: "Europe/Moscow", label: "UTC+03:00 Moscow, St. Petersburg, Volgograd" },
  { value: "Asia/Baghdad", label: "UTC+03:00 Baghdad, Kuwait, Nairobi, Riyadh" },
  { value: "Europe/Bucharest", label: "UTC+03:00 Eastern Europe" },
  { value: "Europe/Minsk", label: "UTC+03:00 Minsk" },
  { value: "Europe/Helsinki", label: "UTC+03:00 Eastern European Time" },
  { value: "Europe/Istanbul", label: "UTC+03:00 Istanbul" },
  { value: "Indian/Antananarivo", label: "UTC+03:00 Antananarivo" },
  { value: "Asia/Jerusalem", label: "UTC+03:00 Israel" },
  { value: "Europe/Athens", label: "UTC+03:00 Athens, Helsinki" },
  { value: "Asia/Tehran", label: "UTC+03:30 Tehran" },
  { value: "Asia/Yerevan", label: "UTC+04:00 Armenia" },
  { value: "Asia/Dubai", label: "UTC+04:00 Abu Dhabi, Muscat, Tbilisi, Kazan" },
  { value: "Asia/Kabul", label: "UTC+04:30 Kabul" },
  { value: "Asia/Karachi", label: "UTC+05:00 Islamabad, Karachi" },
  { value: "Asia/Tashkent", label: "UTC+05:00 Tashkent" },
  { value: "Asia/Almaty", label: "UTC+05:00 Almaty" },
  { value: "Asia/Yekaterinburg", label: "UTC+05:00 Sverdlovsk, Tashkent" },
  { value: "Asia/Kolkata", label: "UTC+05:30 Mumbai, Kolkata, Chennai, New Delhi" },
  { value: "Asia/Kathmandu", label: "UTC+05:45 Kathmandu, Nepal" },
  { value: "Asia/Omsk", label: "UTC+06:00 Omsk, Novosibirsk" },
  { value: "Asia/Dhaka", label: "UTC+06:00 Dhaka" },
  { value: "Asia/Yangon", label: "UTC+06:30 Myanmar" },
  { value: "Asia/Krasnoyarsk", label: "UTC+07:00 Krasnoyarsk" },
  { value: "Asia/Bangkok", label: "UTC+07:00 Bangkok, Jakarta, Hanoi" },
  { value: "Asia/Novosibirsk", label: "UTC+07:00 Novosibirsk" },
  { value: "Asia/Singapore", label: "UTC+08:00 Hong Kong SAR, Perth, Singapore, Taipei" },
  { value: "Asia/Shanghai", label: "UTC+08:00 Beijing, Chongqing, Urumqi" },
  { value: "Asia/Irkutsk", label: "UTC+08:00 Irkutsk (Lake Baikal)" },
  { value: "Asia/Yakutsk", label: "UTC+09:00 Yakutsk (Lena River)" },
  { value: "Asia/Tokyo", label: "UTC+09:00 Tokyo, Osaka, Sapporo, Seoul" },
  { value: "Australia/Darwin", label: "UTC+09:30 Darwin" },
  { value: "Australia/Adelaide", label: "UTC+09:30 Adelaide" },
  { value: "Asia/Vladivostok", label: "UTC+10:00 Magadan, Vladivostok" },
  { value: "Australia/Hobart", label: "UTC+10:00 Hobart" },
  { value: "Pacific/Guam", label: "UTC+10:00 Guam, Port Moresby" },
  { value: "Australia/Sydney", label: "UTC+10:00 Sydney, Melbourne" },
  { value: "Australia/Brisbane", label: "UTC+10:00 Brisbane" },
  { value: "Pacific/Guadalcanal", label: "UTC+11:00 Solomon Islands, New Caledonia" },
  { value: "Pacific/Kwajalein", label: "UTC+12:00 Eniwetok, Kwajalein" },
  { value: "Asia/Kamchatka", label: "UTC+12:00 Kamchatka" },
  { value: "Pacific/Fiji", label: "UTC+12:00 Fiji Islands, Marshall Islands" },
  { value: "Pacific/Auckland", label: "UTC+12:00 Wellington, Auckland" },
  { value: "Pacific/Apia", label: "UTC+13:00 Apia (Samoa)" },
];

// Friendly label for a stored timezone value. Falls back to the raw value so
// older IANA ids that aren't in the list above still render something sane.
const LABEL_BY_VALUE = new Map(TIMEZONES.map((t) => [t.value, t.label]));
export function timezoneLabel(value?: string | null): string {
  if (!value) return "";
  return LABEL_BY_VALUE.get(value) ?? value;
}
