// A starter list of universities for the School autocomplete. Users can also
// type any school not in the list (the field accepts free text).
export const UNIVERSITIES: string[] = [
  // Pakistan
  "Islamia University Bahawalpur (IUB)",
  "University of the Punjab",
  "Quaid-i-Azam University",
  "National University of Sciences and Technology (NUST)",
  "Lahore University of Management Sciences (LUMS)",
  "COMSATS University Islamabad",
  "University of Engineering and Technology (UET) Lahore",
  "FAST National University (NUCES)",
  "University of Karachi",
  "Aga Khan University",
  "Government College University (GCU) Lahore",
  "University of Agriculture Faisalabad",
  "Bahria University",
  "Air University",
  "Virtual University of Pakistan",
  "Allama Iqbal Open University",
  "University of Management and Technology (UMT)",
  "Iqra University",
  "University of Lahore",
  "University of Peshawar",
  "University of Sindh",
  "Mehran University of Engineering and Technology",
  "GIK Institute of Engineering Sciences and Technology",
  "Institute of Business Administration (IBA) Karachi",
  // United States
  "Harvard University",
  "Stanford University",
  "Massachusetts Institute of Technology (MIT)",
  "California Institute of Technology (Caltech)",
  "University of California, Berkeley",
  "University of California, Los Angeles (UCLA)",
  "Northwestern University",
  "Columbia University",
  "Yale University",
  "Princeton University",
  "University of Chicago",
  "Cornell University",
  "University of Michigan",
  "New York University (NYU)",
  "University of Texas at Austin",
  "Georgia Institute of Technology",
  "Carnegie Mellon University",
  "University of Washington",
  // United Kingdom
  "University of Oxford",
  "University of Cambridge",
  "Imperial College London",
  "University College London (UCL)",
  "London School of Economics (LSE)",
  "University of Edinburgh",
  "University of Manchester",
  "King's College London",
  // Canada
  "University of Toronto",
  "University of British Columbia",
  "McGill University",
  "University of Waterloo",
  // Australia
  "University of Melbourne",
  "University of Sydney",
  "Australian National University",
  "University of New South Wales (UNSW)",
  // Asia & Middle East
  "National University of Singapore (NUS)",
  "Nanyang Technological University (NTU)",
  "Tsinghua University",
  "Peking University",
  "University of Tokyo",
  "Indian Institute of Technology (IIT) Delhi",
  "Indian Institute of Technology (IIT) Bombay",
  "University of Delhi",
  "King Saud University",
  "United Arab Emirates University",
  // Europe
  "ETH Zurich",
  "Delft University of Technology",
  "Technical University of Munich",
  "Sorbonne University",
  "KTH Royal Institute of Technology",
];
